### ISSUE TITLE
GLSL/SPIRV, Vulkan and Linux support

### ISSUE THREAD

**Issue by stalkerg** [NVIDIAGameWorks/NVIDIAImageScaling#2]
When?

**Comment by Krteq** [comment]
I just wanted to ask the same question.

**Comment by BreadFish64** [comment]
Vulkan support is already there. It just seems like it's not documented very well.
Define `NIS_DXC 1` and add `-e main` to the compile flags. Then you can compile the HLSL to Vulkan SPIRV with glslangvalidator.
I've implemented it here
https://github.com/BreadFish64/yuzu/commit/2eeed34a6e30b5f3162b5842dd7a8430e322e576
if that helps.

**Comment by abernalnv** [comment]
HLSL/GLSL SPIRV support for VK (including Linux) is part of v1.0.1. 
Please fell free to report a bug if you find any problem. Thank you!
